steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
        ".",
      ]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

  - id: "pull image"
    name: "gcr.io/cloud-builders/docker"
    args: ["pull", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]

options:
  logStreamingOption: STREAM_ON

substitutions:
  _SERVICE_NAME: partnersdemo

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:latest"